GET http://localhost:4000/

###
POST http://localhost:4000/
content-type: application/json

{
    "title": "foo",
    "body": "bar",
    "userId": 1
}


###
PUT http://localhost:4000/
content-type: application/json

{
    "title": "final title"
}
 

//content-type: application/json, এইটা সার্ভার কে বলতে হয় যে ভাই আমি JSON পাঠাচ্ছি. By default, সার্ভার body read করে না 
